module.exports =
  process.env.NODE_ENV === 'production'
    ? []
    : [
        {
          name: 'FELIPE SOUZA FERREIRA',
          registrationNumber: '201704940001',
          crg: 8.3,
          course: 'cbcc',
          email: 'notgoo@gmiau.com',
          isFit: false,
          isConcluding: false,
          isActive: true,
          isForming: true,
          isGraduating: false,
          academicHighlight: false,
          cancelled: false,
          mailingList: 'none',
          mailingListToRemove: 'none',
          mailingListToAdd: 'active',
          term: null,
          cd: false,
          period: null
        },
        {
          name: 'LAURA CARDOSO CASTRO',
          registrationNumber: '201304940002',
          crg: 6.63,
          course: 'cbsi',
          email: 'youngboy@yahoo.com',
          isFit: false,
          isConcluding: false,
          isActive: true,
          isForming: false,
          isGraduating: true,
          academicHighlight: false,
          cancelled: false,
          mailingList: 'none',
          mailingListToRemove: 'none',
          mailingListToAdd: 'active',
          term: null,
          cd: false,
          period: '2018.3'
        },
        {
          name: 'JOSE FERREIRA SILVA',
          registrationNumber: '200504940003',
          crg: 8.3,
          course: 'cbsi',
          email: 'naosouativo@gmail.com',
          isFit: false,
          isConcluding: true,
          isActive: false,
          isForming: false,
          isGraduating: false,
          academicHighlight: false,
          cancelled: false,
          mailingList: 'active',
          mailingListToRemove: 'active',
          mailingListToAdd: 'concluding',
          term: null,
          cd: false,
          period: null
        },
        {
          name: 'ENZO FERREIRA ALVES',
          registrationNumber: '201104940004',
          crg: 7.89,
          course: 'cbcc',
          email: 'slug@gmail.com',
          isFit: false,
          isConcluding: false,
          isActive: true,
          isForming: false,
          isGraduating: true,
          academicHighlight: false,
          cancelled: false,
          mailingList: 'none',
          mailingListToRemove: 'none',
          mailingListToAdd: 'active',
          term: null,
          cd: false,
          period: '2018.4'
        },
        {
          name: 'KAUAN CARVALHO SANTOS',
          registrationNumber: '200604940005',
          crg: 7.897,
          course: 'cbcc',
          email: 'dofuturo@gmail.com.br',
          isFit: false,
          isConcluding: false,
          isActive: false,
          isForming: false,
          isGraduating: false,
          academicHighlight: false,
          cancelled: true,
          mailingList: 'active',
          mailingListToRemove: 'active',
          mailingListToAdd: 'none',
          term: null,
          cd: false,
          period: null
        },
        {
          name: 'EDUARDO ALVES LIMA',
          registrationNumber: '201804940006',
          crg: 6.001,
          course: 'cbcc',
          email: 'oldfashioned33@hotmail.com',
          isFit: false,
          isConcluding: false,
          isActive: true,
          isForming: false,
          isGraduating: false,
          academicHighlight: false,
          cancelled: false,
          mailingList: 'none',
          mailingListToRemove: 'none',
          mailingListToAdd: 'active',
          term: null,
          cd: false,
          period: null
        },
        {
          name: 'JULIAN BARBOSA SANTOS',
          registrationNumber: '199604940007',
          crg: 8.3,
          course: 'cbcc',
          email: 'uneccessary@ufpa.br',
          isFit: false,
          isConcluding: true,
          isActive: false,
          isForming: false,
          isGraduating: false,
          academicHighlight: false,
          cancelled: false,
          mailingList: 'active',
          mailingListToRemove: 'active',
          mailingListToAdd: 'concluding',
          term: null,
          cd: false,
          period: null
        }
      ]
